# Generated by Django 3.2.25 on 2024-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_color',
        ),
        migrations.AddField(
            model_name='product',
            name='color_option',
            field=models.CharField(choices=[('colour', 'Colour'), ('black_and_white', 'Black and White'), ('colour_bw', 'Colour + B&W')], default='colour', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default='This is a great artist.'),
        ),
    ]
