# Generated by Django 3.2.25 on 2024-07-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240731_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('softcover', 'Softcover'), ('hardcover', 'Hardcover')], max_length=50),
        ),
    ]
